feat: show form validation summary when form is submitted
dhis2/import-export-app pull request #687
Opened 2020-09-17 21:14 UTC by awgaan

Addresses:
- DHIS2-9546 (https://jira.dhis2.org/browse/DHIS2-9546)

2020-09-18 12:47 UTC, Birkbjo commented
This seems very complicated for a pretty basic feature. You can get the `errors`-state from the `FormState` pretty easily: https://final-form.org/docs/final-form/types/FormState#errors . So I would just pass that object to the validationForm, or use `useFormState` from the `ValidationSummary`-component.

2020-09-18 12:47 UTC, Birkbjo requested changes
Unless I'm missing something, this seems very complicated for a pretty basic feature. You can get the errors-state from the FormState pretty easily: https://final-form.org/docs/final-form/types/FormState#errors . So I would just pass that object to the validationForm, or use `useFormState` from the ValidationSummary-component.

2020-09-18 16:05 UTC, awgaan commented
You're absolutely right, Birk.
`useFormState` is so much simpler and achieves the same goal.
I over-complicated this issue.

2020-09-21 12:37 UTC, Birkbjo approved these changes

2020-09-21 12:51 UTC, merged